name: Update version.json

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing changes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Update version.json
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Release tag: $TAG_NAME"

          VERSION_FILE="version.json"
          JSON=$(cat $VERSION_FILE)

          JSON=$(echo "$JSON" | jq --arg ver "$TAG_NAME" \
            '.["868"].version=$ver 
             | .["868"].url="https://github.com/${{ github.repository }}/releases/download/\($ver)/meteostazionefirmware_receiver_868.ino.bin" 
             | .["915"].version=$ver 
             | .["915"].url="https://github.com/${{ github.repository }}/releases/download/\($ver)/meteostazionefirmware_receiver_915.ino.bin"')

          echo "$JSON" > $VERSION_FILE
          cat $VERSION_FILE

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.json
          git commit -m "Update version.json for $TAG_NAME" || echo "No changes to commit"
          git push

